## Machine Learning model for Used car sales

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Dataset Loading

In [4]:
df = pd.read_csv("cars_24_combined.csv")

### Preprocessing steps

In [5]:
df.head()

,Unnamed: 0,Car Name,Year,Distance,Owner,Fuel,Location,Drive,Type,Price
0,0,Maruti S PRESSO,2022.0,3878,1,PETROL,HR-98,Manual,HatchBack,514000
1,1,Hyundai Xcent,2018.0,32041,1,PETROL,TN-22,Manual,Sedan,674000
2,2,Tata Safari,2021.0,96339,1,DIESEL,TS-08,Automatic,SUV,1952000
3,3,Maruti Vitara Brezza,2019.0,51718,1,DIESEL,WB-24,Manual,SUV,690000
4,4,Tata Tiago,2021.0,19811,1,PETROL,HR-51,Manual,HatchBack,526000

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8015 entries, 0 to 8014
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  8015 non-null   int64
 1   Car Name    8014 non-null   str
 2   Year        8014 non-null   float64
 3   Distance    8015 non-null   int64
 4   Owner       8015 non-null   int64
 5   Fuel        8015 non-null   str
 6   Location    7802 non-null   str
 7   Drive       8015 non-null   str
 8   Type        8015 non-null   str
 9   Price       8015 non-null   int64
dtypes: float64(1), int64(4), str(5)
memory usage: 928.1 KB

In [7]:
df["Car Name"].value_counts()

Car Name
Maruti Swift           593
Hyundai Grand i10      451
Maruti Baleno          430
Hyundai Elite i20      382
Maruti Wagon R 1.0     362
                      ...
Maruti OMNI E            1
Jeep GRAND CHEROKEE      1
Toyota Fortuner          1
Mahindra MARAZZO         1
Nissan Sunny             1
Name: count, Length: 126, dtype: int64

In [8]:
df.describe()

        Unnamed: 0         Year       Distance        Owner         Price
count  8015.000000  8014.000000    8015.000000  8015.000000  8.015000e+03
mean   4007.000000  2016.995009   52621.411728     1.300187  5.748829e+05
std    2313.875537     2.861454   29182.922728     0.510893  2.651049e+05
min       0.000000  2010.000000       0.000000     1.000000  1.190000e+05
25%    2003.500000  2015.000000   30730.000000     1.000000  3.930000e+05
50%    4007.000000  2017.000000   50359.000000     1.000000  5.350000e+05
75%    6010.500000  2019.000000   71762.000000     2.000000  6.980000e+05
max    8014.000000  2023.000000  971212.000000     4.000000  3.300000e+06

In [9]:
df.shape

(8015, 10)

#### Checking Duplicates

In [10]:
df[df.duplicated()]

Empty DataFrame
Columns: [Unnamed: 0, Car Name, Year, Distance, Owner, Fuel, Location, Drive, Type, Price]
Index: []

#### Handling Null values

In [11]:
df.isnull().sum()

Unnamed: 0      0
Car Name        1
Year            1
Distance        0
Owner           0
Fuel            0
Location      213
Drive           0
Type            0
Price           0
dtype: int64

In [12]:
df.dropna(subset=["Car Name", "Year"], inplace=True)

df["Location"] = df["Location"].fillna("Unknown")

In [13]:
df.drop("Unnamed: 0", axis=1, inplace=True)

In [14]:
df.corr(numeric_only=True)["Price"].sort_values(ascending=False)

Price       1.000000
Year        0.501978
Owner      -0.149838
Distance   -0.198750
Name: Price, dtype: float64

In [15]:
df.columns

Index(['Car Name', 'Year', 'Distance', 'Owner', 'Fuel', 'Location', 'Drive',
       'Type', 'Price'],
      dtype='str')

In [16]:
df.isnull().sum()

Car Name    0
Year        0
Distance    0
Owner       0
Fuel        0
Location    0
Drive       0
Type        0
Price       0
dtype: int64

### Splitting features and target

In [17]:
X = df.drop("Price", axis=1)
Y = df["Price"]

In [18]:
X.head()

,Car Name,Year,Distance,Owner,Fuel,Location,Drive,Type
0,Maruti S PRESSO,2022.0,3878,1,PETROL,HR-98,Manual,HatchBack
1,Hyundai Xcent,2018.0,32041,1,PETROL,TN-22,Manual,Sedan
2,Tata Safari,2021.0,96339,1,DIESEL,TS-08,Automatic,SUV
3,Maruti Vitara Brezza,2019.0,51718,1,DIESEL,WB-24,Manual,SUV
4,Tata Tiago,2021.0,19811,1,PETROL,HR-51,Manual,HatchBack

### Encoding

In [19]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
cat_cols = ["Car Name","Fuel","Location","Drive","Type"]
ct = ColumnTransformer(
    [(
        "encoder",
        OneHotEncoder(
            handle_unknown="ignore",
            sparse_output=False
        ),
        cat_cols
    )],
    remainder="passthrough"
)

X = ct.fit_transform(X)

X = pd.DataFrame(
    X,
    columns=ct.get_feature_names_out()
)

### Train-test split

In [20]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

### Scaling

In [21]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

### MODEL PREDICTION

#### Linear Regression

In [22]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train,Y_train)

LinearRegression()

In [23]:
y_pred = lr.predict(X_test)

In [24]:
from sklearn.metrics import r2_score,mean_absolute_error,root_mean_squared_error,mean_squared_error
print("====Linear Regression====")
print("r2 score",r2_score(Y_test,y_pred))
print("MAE",mean_absolute_error(Y_test,y_pred))
print(root_mean_squared_error(Y_test,y_pred))

====Linear Regression====
r2 score 0.7681252741497795
MAE 75965.01997570558
130746.95769847061

In [25]:
print(type(Y_test))

<class 'pandas.Series'>

### KNN

In [26]:
from sklearn.neighbors import KNeighborsRegressor
knn = KNeighborsRegressor()
knn.fit(X_train,Y_train)
y_pred = knn.predict(X_test)
print("====KNN====")
print("r2 score",r2_score(Y_test,y_pred))
print("MAE",mean_absolute_error(Y_test,y_pred))
mae_percent = (mean_absolute_error(Y_test, y_pred) / Y_test.mean()) * 100
print(f"MAE % = {mae_percent:.2f}%")

====KNN====
r2 score 0.5063736749628858
MAE 125046.35995009358
MAE % = 21.68%

In [27]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators=500,
    max_depth=None,
    )
rf.fit(X_train,Y_train)

RandomForestRegressor(n_estimators=500)

In [28]:
y_pred = rf.predict(X_test)

In [29]:
print("RANDOM FOREST")
print("r2 score",r2_score(Y_test,y_pred)*100)
print("MAE",mean_absolute_error(Y_test,y_pred))

RANDOM FOREST
r2 score 78.40333301127394
MAE 73139.58721147847

### DECISION TREE

In [30]:
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor()
dt.fit(X_train,Y_train)
y_pred = dt.predict(X_test)
print("DECISION TREE")
print("r2 score",r2_score(Y_test,y_pred)*100)
print("MAE",mean_absolute_error(Y_test,y_pred))

DECISION TREE
r2 score 68.47694870478023
MAE 90013.56830941983

### ADABOOST

In [31]:
from sklearn.ensemble import AdaBoostRegressor
ab = AdaBoostRegressor()
ab.fit(X_train,Y_train)
y_pred = ab.predict(X_test)
print("====ADABOOST====")
print("r2 score",r2_score(Y_test,y_pred))
print("MAE",mean_absolute_error(Y_test,y_pred))

====ADABOOST====
r2 score 0.37275423188848267
MAE 171341.3184016322

### GRADIENT BOOST

In [32]:
from sklearn.ensemble import GradientBoostingRegressor
gb = GradientBoostingRegressor()
gb.fit(X_train,Y_train)
y_pred = gb.predict(X_test)
print("====GRADIENT BOOST====")
print("r2 score",r2_score(Y_test,y_pred))
print("MAE",mean_absolute_error(Y_test,y_pred))

====GRADIENT BOOST====
r2 score 0.7267150802677238
MAE 90702.82928812163

### XGBOOST

In [33]:
from xgboost import XGBRegressor
xg = XGBRegressor()
xg.fit(X_train,Y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [34]:
y_pred = xg.predict(X_test)

In [35]:
print("XGBOOST")
print("r2 score",r2_score(Y_test,y_pred)*100)
print("MAE",mean_absolute_error(Y_test,y_pred))

XGBOOST
r2 score 80.02620339393616
MAE 67682.09375

### XGBOOST THROUGH GRIDSEARCHCV

In [36]:
from xgboost import XGBRegressor
from sklearn.model_selection import GridSearchCV
xgb = XGBRegressor(
    objective="reg:squarederror",
    random_state=42
)
param_grid = {
    "n_estimators": [200, 500],
    "max_depth": [4, 6],
    "learning_rate": [0.05, 0.1]
}
grid = GridSearchCV(
    estimator=xgb,
    param_grid=param_grid,
    cv=5,
    scoring="r2",
    n_jobs=-1,    
)
grid.fit(X_train, Y_train)
print("Best Parameters:")
print(grid.best_params_)
print("\nBest CV R²:")
print(grid.best_score_)

Best Parameters:
{'learning_rate': 0.1, 'max_depth': 6, 'n_estimators': 500}

Best CV R²:
0.8409339904785156

In [37]:
best_xgb = grid.best_estimator_

y_pred = best_xgb.predict(X_test)

In [38]:
print("====XGB through GridSearchCV====")
print("r2 score",r2_score(Y_test,y_pred))
print("MAE",mean_absolute_error(Y_test,y_pred))
print("RMSE",root_mean_squared_error(Y_test,y_pred))

====XGB through GridSearchCV====
r2 score 0.8166325092315674
MAE 64801.81640625
RMSE 116269.5625

In [39]:
import joblib
joblib.dump(best_xgb,"model.pkl")
joblib.dump(scaler, "scaler.pkl")  
joblib.dump(ct, "transformer.pkl")

['transformer.pkl']